-- CREATES DB USA
-- CREATES TABLE STATES IN USA DB
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
-- CREATES TABLE STATES IN USA DB
CREATE TABLE IF NOT EXISTS hbtn_0d_usa.states(
    id INT UNIQUE NOT NULL,
    name VARCHAR(256) NOT NULL,
    PRIMARY KEY (id)
);