-- CREATES DB USA
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
-- CREATES TABLE STATES IN USA DB
CREATE TABLE IF NOT EXISTS hbtn_0d_usa.states(
    id INT UNIQUE DEFAULT 1 NOT NULL PRIMARY KEY,
    name VARCHAR(256) NOT NULL
);